
namespacing={init:function(namespace){var spaces=[];namespace.split('.').each(function(space){var curSpace=window,i;spaces.push(space);for(i=0;i<spaces.length;i++){if(typeof curSpace[spaces[i]]==='undefined'){curSpace[spaces[i]]={};}
curSpace=curSpace[spaces[i]];}});}};var PremiereAdmin={premiereSubmitRequest:function(params){$('adminPremiereConfirmButton').stopObserving('click');var url='/ajax_class_creator.php'
var ajaxRequest=new Ajax.Request(url,{method:'post',parameters:params,onComplete:this.premiereActionComplete.bind(this),onFailure:this.premiereActionFailed.bind(this)});},premiereActionComplete:function(req){var premiereResponse=req.responseText
if(premiereResponse=='ajax_fail'){ajaxWin.cancelWindow();alert('An error was encountered while trying to process your request');}
var premiereData=req.responseText.evalJSON(true);if(premiereData.resultStatus==1){$('ajaxWinBody').replace('<p>'+premiereData.resultMessage+'</p>');if($('agencyActions')){$('agencyActions').replace('<p>File can\'t be moved to the Agency Collection.</p>');}
if(premiereData.showlist){premiereData.showlist.each(function(elm){if($(elm)){$(elm).show();}});}
if(premiereData.hidelist){premiereData.hidelist.each(function(elm){if($(elm)){$(elm).hide();}});}
if(premiereData.showfade){var contButton='';}else{var contButton='<a class="btn_orange" onclick="ajaxWin.cancelWindow(); return false;" href="#">Continue</a>'+'<div class = "clear"></div>';}
ajaxWin.show({title:premiereData.resultTitle,cntnt:"<p style=\"padding:0 10px\">"+premiereData.resultMessage+"</p>",wdth:400,footer:contButton});if(premiereData.showfade){$('ajaxWin').fade({duration:3,afterFinish:function(){ajaxWin.cancelWindow();}});}}else if(premiereData.resultStatus==0){ajaxWin.show({title:premiereData.resultTitle,cntnt:'<p class = "error" style=\"padding:0 10px\">Failed to complete request!!<br/>'+premiereData.resultMessage+'</p>',wdth:400,footer:'<a class="btn_orange" onclick="ajaxWin.cancelWindow(); return false;" href="#">Continue</a>'+'<div class = "clear"></div>'});}else{alert('Unknown response received when submitting request!!');}},premiereActionFailed:function(req){alert('There was a problem trying to process your request. Try again.');},confirmReInstate:function(userID){ajaxWin.show({title:'Confirm Contributor file ReInstatement',cntnt:"<p style=\"padding:0 10px\">Are you sure you want to mark all the user's cancelled Vetta files as Approved? Only the files that were "+"previously Approved will be Re-Instated. Files that were not yet approved will remain cancelled.</p>",wdth:400,footer:'<a class="btn_orange fl" onclick="ajaxWin.cancelWindow(); return false;" href="#">No</a>'+'<a id = "adminPremiereConfirmButton" class="btn_orange fr" href="" onclick = "return false;">Yes</a>'+'<div class = "clear"></div>'});$('adminPremiereConfirmButton').observe('click',function(event){PremiereAdmin.submitReInstate(userID);});},submitReInstate:function(userID){var params='ajax_action=reInstatePremiereNomination&ajax_class=editorqueue'+'&userID='+userID;this.premiereSubmitRequest(params);},confirmPremiereNomination:function(fileID){var priceOptionsForm=$('priceOptionsRadio_'+fileID);if(priceOptionsForm!=null){var priceOption=priceOptionsForm.getInputs('radio').find(function(radio){return radio.checked;}).value;}
ajaxWin.show({title:'Add to Vetta Collection?',cntnt:'<p style=\"padding:0 10px\">Are you sure you want to move this file to the Vetta Collection?</p>',wdth:400,footer:'<a class="btn_orange fl" onclick="ajaxWin.cancelWindow(); return false;" href="#">No</a>'+'<a id = "adminPremiereConfirmButton" class="btn_orange fr" href="" onclick = "return false;" >Yes</a>'+'<div class = "clear"></div>'});$('adminPremiereConfirmButton').observe('click',function(event){PremiereAdmin.submitPremiereNomination(fileID,priceOption);});},submitPremiereNomination:function(fileID,priceOption){var params='ajax_class=editorqueue&ajax_action=nominateFile'+'&fileID='+fileID;if(priceOption){params+='&priceOption='+priceOption;}
this.premiereSubmitRequest(params);},confirmCancelFileNomination:function(fileID){ajaxWin.show({title:'Confirm nomination cancellation',cntnt:'<p style=\"padding:0 10px\">Are you sure you want to remove this file from the Vetta Collection?</p>',wdth:400,footer:'<a class="btn_orange fl" onclick="ajaxWin.cancelWindow(); return false;" href="#">No</a>'+'<a id = "adminPremiereConfirmButton" class="btn_orange fr" href="" onclick = "return false;">Yes</a>'+'<div class = "clear"></div>'});$('adminPremiereConfirmButton').observe('click',function(event){PremiereAdmin.submitPremiereFileCancel(fileID);});},submitPremiereFileCancel:function(fileID){var params='ajax_class=editorqueue&ajax_action=cancelFileNomination'+'&fileID='+fileID;this.premiereSubmitRequest(params);},confirmPremiereMove:function(fileID){var priceOptionsForm=$('priceOptionsRadio_'+fileID);if(priceOptionsForm!=null){var priceOption=priceOptionsForm.getInputs('radio').find(function(radio){return radio.checked;}).value;}
ajaxWin.show({title:'Add to Vetta Collection?',cntnt:'<p style=\"padding:0 10px\">Are you sure you want to move this file to the Vetta Collection?</p>',wdth:400,footer:'<a class="btn_orange fl" onclick="ajaxWin.cancelWindow(); return false;" href="#">No</a>'+'<a id = "adminPremiereConfirmButton" class="btn_orange fr" href="" onclick = "return false;" >Yes</a>'+'<div class = "clear"></div>'});$('adminPremiereConfirmButton').observe('click',function(event){PremiereAdmin.submitPremiereMove(fileID,priceOption);});},submitPremiereMove:function(fileID,priceOption){var params='ajax_class=editorqueue&ajax_action=approveFileNomination'+'&fileID='+fileID;if(priceOption){params+='&priceOption='+priceOption;}
this.premiereSubmitRequest(params);},agencySubmitRequest:function(params){$('adminAgencyConfirmButton').stopObserving('click');var url='/ajax_class_creator.php'
var ajaxRequest=new Ajax.Request(url,{method:'post',parameters:params,onComplete:this.agencyActionComplete.bind(this),onFailure:this.premiereActionFailed.bind(this)});},agencyActionComplete:function(req){var premiereResponse=req.responseText
if(premiereResponse=='ajax_fail'){ajaxWin.cancelWindow();alert('An error was encountered while trying to process your request');return;}
var premiereData=req.responseText.evalJSON(true);if(premiereData.resultStatus==1){$('ajaxWinBody').replace('<p>'+premiereData.resultMessage+'</p>');if($('premierNominationActions')){$('premierNominationActions').replace('<p>File can\'t be moved to a Vetta collection.</p>');}
if(premiereData.showfade){var contButton='';}else{var contButton='<a class="btn_orange" onclick="ajaxWin.cancelWindow(); return false;" href="#">Continue</a>'+'<div class = "clear"></div>';}
ajaxWin.show({title:premiereData.resultTitle,cntnt:"<p style=\"padding:0 10px\">"+premiereData.resultMessage+"</p>",wdth:400,footer:contButton});if(premiereData.showfade){$('ajaxWin').fade({duration:3,afterFinish:function(){ajaxWin.cancelWindow();}});}}else if(premiereData.resultStatus==0){ajaxWin.show({title:premiereData.resultTitle,cntnt:'<p class = "error" style=\"padding:0 10px\">Failed to complete request!!<br/>'+premiereData.resultMessage+'</p>',wdth:400,footer:'<a class="btn_orange" onclick="ajaxWin.cancelWindow(); return false;" href="#">Continue</a>'+'<div class = "clear"></div>'});}else{alert('Unknown response received when submitting request!!');}},confirmAgencyMove:function(fileID){ajaxWin.show({title:'Add to Agency Collection?',cntnt:'<p style=\"padding:0 10px\">Are you sure you want to move this file to the Agency Collection?</p>',wdth:400,footer:'<a class="btn_orange fl" onclick="ajaxWin.cancelWindow(); return false;" href="#">No</a>'+'<a id = "adminAgencyConfirmButton" class="btn_orange fr" href="" onclick = "return false;" >Yes</a>'+'<div class = "clear"></div>'});$('adminAgencyConfirmButton').observe('click',function(event){PremiereAdmin.submitAgencyMove(fileID);});},submitAgencyMove:function(fileID){var params='ajax_class=editorqueue&ajax_action=approveFileAgency'+'&fileID='+fileID;this.agencySubmitRequest(params);},submitAgencyFileCancel:function(fileID){var params='ajax_class=editorqueue&ajax_action=cancelFileNomination'+'&fileID='+fileID;this.premiereSubmitRequest(params);},confirmCancelAgencyNomination:function(fileID){ajaxWin.show({title:'Confirm removal from Agency Collection',cntnt:'<p style=\"padding:0 10px\">Are you sure you want to remove this file from the Agency Collection?</p>',wdth:400,footer:'<a class="btn_orange fl" onclick="ajaxWin.cancelWindow(); return false;" href="#">No</a>'+'<a id = "adminAgencyConfirmButton" class="btn_orange fr" href="" onclick = "return false;">Yes</a>'+'<div class = "clear"></div>'});$('adminAgencyConfirmButton').observe('click',function(event){PremiereAdmin.submitAgencyFileCancel(fileID);});},submitAgencyFileCancel:function(fileID){var params='ajax_class=editorqueue&ajax_action=cancelFileAgency'+'&fileID='+fileID;this.agencySubmitRequest(params);}}